# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "zh"

pipeline:
  - name: "rasa_nlu_addons.utils.tensorflow_utils.TensorflowNLP"
#  - name: "rasa_nlu_addons.debugger.tensorflow_debugger.TensorflowDebugger"
  - name: "rasa_nlu_addons.extractors.bilstm_crf_tf_entity_extractor.BilstmCrfTensorFlowEntityExtractor"
    max_steps: 600
#    train_hook:
#      - class: "rasa_nlu_addons.debugger.hooks.TensorObserveHook"
#        params:
#          key: "34FRerfFefsdKer4hdF"

  - name: "rasa_nlu_addons.classifiers.text_cnn_tf_classifier.TextCnnTensorFlowClassifier"
    max_steps: 600

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
