language: en
pipeline:
- name: SpacyNLP
  model: "en_core_web_md"
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: CountVectorsFeaturizer
- name: SklearnIntentClassifier
- name: CRFEntityExtractor
  features: [["low", "title"], ["bias", "suffix3"], ["upper", "pos", "pos2"]]
  BILOU_flag: true
- name: EntitySynonymMapper

policies:
- epochs: 50
  max_history: 6
  name: KerasPolicy
- max_history: 6
  name: AugmentedMemoizationPolicy
- name: FormPolicy
- name: MappingPolicy